### ISSUE TITLE
Changes to schedule schemas

### ISSUE THREAD

**Issue by ebeshero** [ebeshero/UpTransformation#15]
Relax NG 
- [x] Make a start date that's metadata in the XML.
- [x] Calculate all dates from the start date.
- [x] This requires changes in the XSLT.
- [x] Make it easier and more semantically meaningful to navigate from the top level between collapsed vs. expanded view. All lists should be ordered lists. (Change XSLT and JS accordingly.)
* Hierarchies start with upper Latin
* A. 1. a. i.  1)
* B. 2. b. ii. b)

XSLT

Schematron

- [ ]

**Comment by djbpitt** [comment]
Done!
