### ISSUE TITLE
Link to older versions of the course

### ISSUE THREAD

**Issue by djbpitt** [ebeshero/UpTransformation#17]
The link to older versions of the course on the Resources page, which currently points to the 2018 version, is broken. Additionally, we should move those links to the bottom of the page, since they're likely to be less in demand than information about where to learn more.

**Comment by ebeshero** [comment]
Repaired (removed link) with https://github.com/ebeshero/UpTransformation/commit/00499a86cb438f71a3f7d0aa4ddbfd92310e9c14
