### ISSUE TITLE
xsl:result-document and xsl:message

### ISSUE THREAD

**Issue by ebeshero** [ebeshero/UpTransformation#2]
This example from the Obdurodon Immigration Station project reads from a `collection()` and outputs multiple files using `<xsl:result-document>`: https://github.com/ech45/immigration_station/blob/master/Mallet/extract-mallet-input-data.xsl

`<xsl:result-document>` and `<xsl:message>` are useful for "micropipeline" processes to send out intermediary files or posts during processing--and almost certainly would be beneficial for up-conversion. 

`<xsl:message>` : writes a message to standard error (which can be read in oXygen's lower left tabs).

**Comment by djbpitt** [comment]
Done!
