### ISSUE TITLE
Create syllabus schema and transformations

### ISSUE THREAD

**Issue by djbpitt** [ebeshero/UpTransformation#4]
- [x] Create Relax NG (optional: also Schematron)
- [x] Transfer schedule outline to XML
- [x] Create XSLT to transform XML into overview syllabus
- [x] Create XSLT to transform XML into detail session plans\

**Comment by djbpitt** [comment]
@ebeshero I’ve drafted scheduling tools inside a `schedule` subdirectory: xml, rnc, sch, plus xslt to convert to a full-schedule view (xhtml) for our use (we can also create a streamlined one, perhaps without the time stamps, for participant use). The durations are sort of arbitrary, just to ensure that Schematron was correctly verifying that they added up correctly. I learned some interesting things about working with durations while writing this, so I'm happy to have done it for that reason, as well.

If anything about the schemas and transformation isn’t self-explanatory, please ask; otherwise, please let me know what you think we should modify—with respect to both the scheduling tools and the schedule itself. I think, for example, that we should have links to tutorial pages, whether we create them for DHSI or (more likely) link to those we already have on Newtfire and Obdurodon, but I haven’t built that into the schema yet. If you’d like to review this first version and reply with suggestions for additions or corrections, I’ll be happy to make a second pass at it.

**Comment by djbpitt** [comment]
@ebeshero There are now two copies of `schedule-full.html` in the repo, one inside `_includes` and the other inside `_includes/schedule`. We should have just one, but which one do we want?

**Comment by ebeshero** [comment]
@djbpitt We want the one inside `_includes/schedule/`. Sorry about that--I thought I removed the one outside, and will remove it now.

**Comment by djbpitt** [comment]
Done!
